package org.jeecg.modules.demo.dzzz.spht.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.jeecg.modules.demo.dzzz.spht.entity.TYwZsN;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * @Description: t_yw_zs_n
 * @Author: jeecg-boot
 * @Date:   2024-07-16
 * @Version: V1.0
 */
public interface TYwZsNMapper extends BaseMapper<TYwZsN> {


    /*int saveSpDateHt(@Param("id") String id,
                     @Param("qyid")String qyid,
                     @Param("zslx")String zslx,
                     @Param("zsbh")String zsbh,
                     @Param("qymc")String qymc,
                     @Param("shxydm")String shxydm,
                     @Param("zcdz")String zcdz,
                     @Param("fddbr")String fddbr,
                     @Param("qyfzr")String qyfzr,
                     @Param("zlfzr")String zlfzr,
                     @Param("flm")String flm,
                     @Param("rcjdgljg")String rcjdgljg,
                     @Param("rcjdglry")String rcjdglry,
                     @Param("scdzhfw")String scdzhfw,
                     @Param("fzjg")String fzjg,
                     @Param("qfr")String qfr,
                     @Param("fzrq")String fzrq,
                     @Param("yxqq")String yxqq,
                     @Param("yxqz")String yxqz,
                     @Param("scdz")String scdz,
                     @Param("slh")String slh,
                     @Param("ckdz")String ckdz,
                     @Param("jgjzc")String jgjzc,
                     @Param("fw")String fw,
                     @Param("fwyw")String fwyw,
                     @Param("bz")String bz,
                     @Param("zs")String zs,
                     @Param("cs")String cs,
                     @Param("cp")String cp,
                     @Param("cplb")String cplb,
                     @Param("cpmx")String cpmx,
                     @Param("dh")String dh,
                     @Param("cz")String cz,
                     @Param("gg")String gg,
                     @Param("jx")String jx,
                     @Param("fj")String fj,
                     @Param("wzym")String wzym,
                     @Param("jsly")String jsly,
                     @Param("zt")String zt,
                     @Param("ywlb")String ywlb,
                     @Param("bbid")String bbid,
                     @Param("mbid")String mbid,
                     @Param("ylzd1")String ylzd1,
                     @Param("ylzd2")String ylzd2,
                     @Param("ylzd3")String ylzd3,
                     @Param("ylzd4")String ylzd4,
                     @Param("ylzd5")String ylzd5,
                     @Param("fzjgid")String fzjgid,
                     @Param("sjtb_zsgs")String sjtb_zsgs,
                     @Param("sjtb_da")String sjtb_da,
                     @Param("sjtb_xzsp")String sjtb_xzsp,
                     @Param("sjtb_gj")String sjtb_gj,
                     @Param("sjtb_cwxx")String sjtb_cwxx,
                     @Param("sjtb_gjsj")String sjtb_gjsj,
                     @Param("ylzd6")String ylzd6,
                     @Param("ylzd7")String ylzd7,
                     @Param("ylzd8")String ylzd8,
                     @Param("ylzd9")String ylzd9,
                     @Param("ylzd10")String ylzd10,
                     @Param("ylzd11")String ylzd11,
                     @Param("ylzd12")String ylzd12,
                     @Param("ylzd13")String ylzd13,
                     @Param("ylzd14")String ylzd14,
                     @Param("ylzd15")String ylzd15,
                     @Param("ylzd16")String ylzd16,
                     @Param("ylzd17")String ylzd17,
                     @Param("ylzd18")String ylzd18,
                     @Param("ylzd19")String ylzd19,
                     @Param("ylzd20")String ylzd20,
                     @Param("ylzd21")String ylzd21,
                     @Param("ylzd22")String ylzd22,
                     @Param("ylzd23")String ylzd23,
                     @Param("ylzd24")String ylzd24,
                     @Param("ylzd25")String ylzd25,
                     @Param("ylzd26")String ylzd26,
                     @Param("ylzd27")String ylzd27,
                     @Param("ylzd28")String ylzd28,
                     @Param("ylzd29")String ylzd29,
                     @Param("ylzd30")String ylzd30,
                     @Param("ylzd31")String ylzd31,
                     @Param("ylzd32")String ylzd32,
                     @Param("ylzd33")String ylzd33,
                     @Param("ylzd34")String ylzd34,
                     @Param("ylzd35")String ylzd35,
                     @Param("ylzd36")String ylzd36,
                     @Param("ylzd37")String ylzd37,
                     @Param("ylzd38")String ylzd38,
                     @Param("ylzd39")String ylzd39,
                     @Param("ylzd40")String ylzd40,
                     @Param("ewm")String ewm,
                     @Param("ewmlj")String ewmlj,
                     @Param("sync")String sync,
                     @Param("glzdb")String glzdb,
                     @Param("qylx")String qylx,
                     @Param("lxryx")String lxryx,
                     @Param("lxdh")String lxdh,
                     @Param("typelevel")String typelevel,
                     @Param("mobile")String mobile);*/


}
